### ISSUE TITLE
Secrets uploaded

### ISSUE THREAD

**Issue by Plazmaz** [kvinzheng/InTuneNation_Backend#23]
Hello! Sorry to bother you, but I noticed you uploaded some stuff you probably didn't mean to in this commit:
https://github.com/kvinzheng/PPPbackend-route/commit/3d49b0f9538a86a94e625e5a67a71edb6b7f5510
Git stores history of everything, so even removing these files won't wipe them from the internet. You should change any data involved in that commit that you don't want to be public. It also looks like you attempted to add your clientId and secret to your gitignore, by doing so, you actually highlighted them for me. As you can see, that information is public here:
https://github.com/kvinzheng/PPPbackend-route/blob/3d49b0f9538a86a94e625e5a67a71edb6b7f5510/.gitignore
I strongly suggest changing your oauth tokens JWT key, as they are now public  I also suggest doing further research into the .gitignore file, as it only allows for the exclusion of files by name, not by contents.

Have a nice day,
~Dylan

**Comment by kvinzheng** [comment]
Thanks for pointing the error out. I have changed the google ID along with the JWT key.

**Comment by Plazmaz** [comment]
Good to hear it. Good luck with your project.
